name: Publish
on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish Package
    environment: npm
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # for OIDC
      contents: write # for tag push
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # setup
      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: 24
          cache: "npm"
          registry-url: 'https://registry.npmjs.org'
      
      - name: update npm
        run: npm install -g npm@11.6.2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # create release
      - name: Get version from package.json
        id: version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git tag "v${{ steps.version.outputs.version }}"
          git push origin "v${{ steps.version.outputs.version }}"

      - name: Release
        uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090 # v2
        with:
          tag_name: "v${{ steps.version.outputs.version }}"
          generate_release_notes: true

      # deploy
      - name: Publish to npm
        run: npm publish
